# -*- coding: utf-8 -*-
"""Fashion_chatbot_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PiwxBOlmyHoTaOHYaT45mXW67-s0uVyT
"""

# =========================
# 1. Install dependencies
# =========================

!pip install -q gradio pypdf python-dotenv torch
!pip install -q llama-index llama-index-llms-llama-cpp
!pip install -q llama-index-embeddings-langchain
!pip install -q langchain langchain-community sentence-transformers
!pip install -q qdrant-client

# =========================
# 2. Mount Google Drive
# =========================

from google.colab import drive
drive.mount("/content/drive")

/content/drive/MyDrive/Data/fashsion.pdf

# =========================
# 3. Imports
# =========================

import logging
import sys
import torch
import gradio as gr

from llama_index.core import Settings, VectorStoreIndex, SimpleDirectoryReader
from llama_index.llms.llama_cpp import LlamaCPP
from llama_index.llms.llama_cpp.llama_utils import (
    messages_to_prompt,
    completion_to_prompt,
)

from llama_index.embeddings.langchain import LangchainEmbedding
from langchain_community.embeddings import HuggingFaceEmbeddings

# =========================
# 5. Load PDF documents
# =========================

PDF_PATH = "/content/drive/MyDrive/Data/fashsion.pdf"

documents = SimpleDirectoryReader(
    input_files=[PDF_PATH]
).load_data()

print(f"Loaded {len(documents)} document pages")

# =========================
# 6. Setup local LLM
# =========================

llm = LlamaCPP(
    model_url="https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q4_K_M.gguf",
    model_path=None,
    temperature=0.1,
    max_new_tokens=256,
    context_window=3900,
    generate_kwargs={},
    model_kwargs={
        "n_gpu_layers": -1 if torch.cuda.is_available() else 0
    },
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose=True,
)

# =========================
# 7. Setup embedding model
# =========================

embed_model = LangchainEmbedding(
    HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2",
        model_kwargs={
            "device": "cuda" if torch.cuda.is_available() else "cpu"
        }
    )
)

# =========================
# 8. Configure LlamaIndex
# =========================

Settings.llm = llm
Settings.embed_model = embed_model
Settings.chunk_size = 512
Settings.chunk_overlap = 50

# =========================
# 9. Build index and query engine
# =========================

index = VectorStoreIndex.from_documents(
    documents,
    show_progress=True
)

query_engine = index.as_query_engine(
    similarity_top_k=3
)

# =========================
# 10. Test query
# =========================

response = query_engine.query("What is this document about?")
print(response)

# =========================
# 11. Gradio chatbot
# =========================

def chatbot_response(message, history):
    response = query_engine.query(message)
    return str(response)

demo = gr.ChatInterface(
    fn=chatbot_response,
    title="Fashion Chatbot System",
    description="Ask questions about the uploaded fashion PDF."
)

demo.launch(debug=True)